rm actualDayplan_1.png
rm dayplanMenus.png
rm edit_schedulePlus.ini.png
rm edit_set2.png
rm flagDE.png
rm flagUS.png
rm getGeoPositionG.png
rm getGeoPositionR.png
rm jobdef_0.png
rm MainMenu.png
rm Tagesplan_Dialoge_0.png
rm Tagesplan_Dialoge.png
